# Default values for sample-dotnet-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.99.1:5000/resideo/sample-dotnet-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

secret:
  name: sample-dotnet-app-config

env:
  valuesServiceType: simple
